# This is a basic workflow to help you get started with Actions

name: releases-tag-deploy

on:
  push:
    tags: 
      - v[0-9].[0-9].[0-9]
      - v[0-9].[0-9].[0-9]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2
        with:
#           java-version: 1.8
          java-version: '11'
          distribution: 'adopt'
          server-id: oss
          # Nexus用户名环境变量
          server-username: MAVEN_USERNAME
          # Nexus密码环境变量
          server-password: MAVEN_PASSWORD
          # gpg短密码环境变量
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          # gpg私钥
          gpg-private-key: ${{ secrets.OSS_GPG_SECRET }}  
          
        
      - name: Publish package
        run: | 
          cd parent
          mvn -B -e -U clean deploy -P release -T32
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSS_GPG_PASSPHRASE }}
